
import __ASTRO_IMAGE_IMPORT_8XHoo from "../../assets/work/wish.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2FInvasion_s3.mdx";
import __ASTRO_IMAGE_IMPORT_Z2vF4h6 from "../../assets/work/alien.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Falien.mdx";
import __ASTRO_IMAGE_IMPORT_Z1pBKce from "../../assets/work/audi.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Faudi.mdx";
import __ASTRO_IMAGE_IMPORT_Z1WqAHz from "../../assets/work/wish.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fcapstone.mdx";
import __ASTRO_IMAGE_IMPORT_1T5Okz from "../../assets/work/dnd.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fdungeon_n_dragon.mdx";
import __ASTRO_IMAGE_IMPORT_ZzzpkC from "../../assets/work/obiwan.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fequalizer.mdx";
import __ASTRO_IMAGE_IMPORT_Pa7KF from "../../assets/work/elemental.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Felemental.mdx";
import __ASTRO_IMAGE_IMPORT_Z2dVUba from "../../assets/work/jurassic.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fjurrassic.mdx";
import __ASTRO_IMAGE_IMPORT_1NjkYO from "../../assets/work/mando3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fmandalorian.mdx";
import __ASTRO_IMAGE_IMPORT_1irsPe from "../../assets/work/byprocession.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fbyprocession.mdx";
import __ASTRO_IMAGE_IMPORT_1LXJkH from "../../assets/work/moana2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fmoana.md";
import __ASTRO_IMAGE_IMPORT_nRTYE from "../../assets/work/obiwan.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fobiwan.mdx";
import __ASTRO_IMAGE_IMPORT_Z2f90PE from "../../assets/work/wish.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Frestless.mdx";
import __ASTRO_IMAGE_IMPORT_2bIAGy from "../../assets/work/wish.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fornamic.mdx";
import __ASTRO_IMAGE_IMPORT_1zdOvT from "../../assets/work/wish.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fsuperman.mdx";
import __ASTRO_IMAGE_IMPORT_GLtRi from "../../assets/work/byprocession.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fwater_drops_on_windows.mdx";
import __ASTRO_IMAGE_IMPORT_12YQNF from "../../assets/work/wish.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fwish.mdx";
export default new Map([["../../assets/work/wish.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2FInvasion_s3.mdx", __ASTRO_IMAGE_IMPORT_8XHoo], ["../../assets/work/alien.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Falien.mdx", __ASTRO_IMAGE_IMPORT_Z2vF4h6], ["../../assets/work/audi.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Faudi.mdx", __ASTRO_IMAGE_IMPORT_Z1pBKce], ["../../assets/work/wish.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fcapstone.mdx", __ASTRO_IMAGE_IMPORT_Z1WqAHz], ["../../assets/work/dnd.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fdungeon_n_dragon.mdx", __ASTRO_IMAGE_IMPORT_1T5Okz], ["../../assets/work/obiwan.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fequalizer.mdx", __ASTRO_IMAGE_IMPORT_ZzzpkC], ["../../assets/work/elemental.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Felemental.mdx", __ASTRO_IMAGE_IMPORT_Pa7KF], ["../../assets/work/jurassic.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fjurrassic.mdx", __ASTRO_IMAGE_IMPORT_Z2dVUba], ["../../assets/work/mando3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fmandalorian.mdx", __ASTRO_IMAGE_IMPORT_1NjkYO], ["../../assets/work/byprocession.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fbyprocession.mdx", __ASTRO_IMAGE_IMPORT_1irsPe], ["../../assets/work/moana2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fmoana.md", __ASTRO_IMAGE_IMPORT_1LXJkH], ["../../assets/work/obiwan.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fobiwan.mdx", __ASTRO_IMAGE_IMPORT_nRTYE], ["../../assets/work/wish.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Frestless.mdx", __ASTRO_IMAGE_IMPORT_Z2f90PE], ["../../assets/work/wish.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fornamic.mdx", __ASTRO_IMAGE_IMPORT_2bIAGy], ["../../assets/work/wish.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fsuperman.mdx", __ASTRO_IMAGE_IMPORT_1zdOvT], ["../../assets/work/byprocession.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fwater_drops_on_windows.mdx", __ASTRO_IMAGE_IMPORT_GLtRi], ["../../assets/work/wish.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fwish.mdx", __ASTRO_IMAGE_IMPORT_12YQNF]]);
		